# Generated by Django 5.0.6 on 2024-11-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('next_period', models.CharField(default='Not set', max_length=50)),
                ('cycle_length', models.CharField(default='Not set', max_length=50)),
                ('last_period', models.CharField(default='Not set', max_length=50)),
                ('tracked_cycles', models.IntegerField(default=0)),
                ('logged_symptoms', models.IntegerField(default=0)),
            ],
        ),
    ]
