# Generated by Django 5.0.6 on 2024-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cycle_length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='next_period',
            field=models.CharField(max_length=50),
        ),
    ]
