# Generated by Django 5.0.6 on 2024-11-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_cycle_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cycle_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_period',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='next_period',
            field=models.FloatField(),
        ),
    ]
