# Generated by Django 5.0.6 on 2024-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_endobot_periods_quizes_stories_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='quiz_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cycle_length',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_period',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='logged_symptoms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='next_period',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tracked_cycles',
        ),
        migrations.AddField(
            model_name='quizes',
            name='quiz_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='quizes',
            name='quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
